// packages/svelte/src/Breadcrumb.svelte
<script lang="ts">
  import { deriveSeed } from '@obscrd/core'

  import { getObscrd } from './context.js'
  import { srOnly } from './styles.js'

  // ── Props ──

  interface Props {
    id?: string
  }

  let { id }: Props = $props()

  // ── Context ──

  const { config } = getObscrd()

  // ── Derived ──

  const contentId = $derived(id ?? deriveSeed(config.seed, 'breadcrumb').slice(0, 8))
</script>

<span aria-hidden="true" data-obscrd-breadcrumb={contentId} style={srOnly}>
  {contentId}
</span>

// packages/angular/src/breadcrumb.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core'
import { deriveSeed } from '@obscrd/core'
import { ObscrdService } from './obscrd.service'
import { srOnly } from './styles'

@Component({
  selector: 'obscrd-breadcrumb',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span
      aria-hidden="true"
      [attr.data-obscrd-breadcrumb]="contentId()"
      [attr.style]="srOnlyStyle"
    >{{ contentId() }}</span>
  `,
})
export class BreadcrumbComponent {
  private readonly obscrd = inject(ObscrdService)

  readonly breadcrumbId = input<string | undefined>(undefined, { alias: 'id' })

  readonly srOnlyStyle = srOnly

  readonly contentId = computed(() => {
    const id = this.breadcrumbId()
    if (id) return id
    return deriveSeed(this.obscrd.config().seed, 'breadcrumb').slice(0, 8)
  })
}
