// packages/react/src/breadcrumb.tsx
import { deriveSeed } from '@obscrd/core'
import { forwardRef, useMemo } from 'react'
import { useObscrdContext } from './provider'
import { srOnly } from './styles'

export interface BreadcrumbProps {
  id?: string
}

export const Breadcrumb = forwardRef<HTMLSpanElement, BreadcrumbProps>(function Breadcrumb({ id }, ref) {
  const { config } = useObscrdContext()

  const contentId = useMemo(() => {
    if (id) return id
    return deriveSeed(config.seed, 'breadcrumb').slice(0, 8)
  }, [id, config.seed])

  if (process.env.NODE_ENV !== 'production' && !id) {
    console.warn(
      '[obscrd] Breadcrumb without an explicit `id` — all breadcrumbs with the same seed will share the same ID. Pass a unique `id` for forensic tracking.',
    )
  }

  return (
    <span ref={ref} aria-hidden="true" data-obscrd-breadcrumb={contentId} style={srOnly}>
      {contentId}
    </span>
  )
})

Breadcrumb.displayName = 'Breadcrumb'

// packages/svelte/src/Breadcrumb.svelte
<script lang="ts">
  import { deriveSeed } from '@obscrd/core'

  import { getObscrd } from './context.js'
  import { srOnly } from './styles.js'

  // ── Props ──

  interface Props {
    id?: string
  }

  let { id }: Props = $props()

  // ── Context ──

  const { config } = getObscrd()

  // ── Derived ──

  const contentId = $derived(id ?? deriveSeed(config.seed, 'breadcrumb').slice(0, 8))
</script>

<span aria-hidden="true" data-obscrd-breadcrumb={contentId} style={srOnly}>
  {contentId}
</span>
